# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Crear archivo .env desde secrets
      run: |
        echo "$PROD_ENV_FILE" > .env
      env:
        PROD_ENV_FILE: ${{ secrets.PROD_ENV_FILE }}
        
    - name: Crear archivo de credenciales Firebase
      run: |
        mkdir -p firebase
        echo "$FIREBASE_KEY" | base64 -d > firebase/yantzazaexpress-d1e68-firebase-adminsdk-fbsvc-f37898d82c.json
      env:
        FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
